package badgerlog.networktables;

import badgerlog.Dashboard;
import badgerlog.annotations.StructType;
import badgerlog.annotations.configuration.Configuration;
import badgerlog.utilities.TypeParser;
import edu.wpi.first.util.struct.Struct;
import edu.wpi.first.util.struct.StructFetcher;
import edu.wpi.first.util.struct.StructSerializable;

import java.util.Optional;

/**
 * Creates a {@link NTEntry} from a key, value, and configuration.
 */
public final class EntryFactory {
    private EntryFactory() {
    }

    /**
     * Creates a new {@link NTEntry} from the specified key, value, and configuration.
     *
     * @param key the key on NetworkTables
     * @param value the value to use with NetworkTables
     * @param config the configuration for the specified value
     * @param <T> the type to use
     *
     * @return a new NTEntry that matches the value and configuration
     */
    @SuppressWarnings("unchecked")
    public static <T> NTEntry<T> createNetworkTableEntryFromValue(String key, T value, Configuration config) {
        Class<T> valueTypeClass = (Class<T>) value.getClass();

        if (StructSerializable.class.isAssignableFrom(valueTypeClass)) {
            Optional<Struct<?>> structOptional = StructFetcher.fetchStructDynamic(valueTypeClass);
            if (structOptional.isPresent()) {

                Struct<T> struct = (Struct<T>) structOptional.get();
                StructType option = config.getStructType() == null ? Dashboard.config.getStructType() : config
                        .getStructType();

                return switch (option) {
                    case STRUCT -> new StructValueEntry<>(key, struct, value);
                    case SUB_TABLE -> new SubtableEntry<>(key, struct, value);
                    case MAPPING -> new ValueEntry<>(key, valueTypeClass, value, config);
                };
            }
        }

        if (config.isAutoGenerateStruct()) {
            TypeParser.generateStructFromTypeIfPossible(config, value.getClass());

            StructType option = config.getStructType() == null ? Dashboard.config.getStructType() : config
                    .getStructType();
            Struct<T> generatedStruct = (Struct<T>) config.getAutoGeneratedStruct();

            if (generatedStruct != null) {
                return option == StructType.SUB_TABLE ? new SubtableEntry<>(key, generatedStruct, value) : new StructValueEntry<>(key, generatedStruct, value);
            }
        }

        return new ValueEntry<>(key, valueTypeClass, value, config);
    }
}
